[package]
name = "serde-java"
version = "0.0.1"
edition = "2024"

[build-dependencies]
string_cache_codegen = "0.7"

[dependencies]
log = "0.4"
thiserror = "2.0"
anyhow = "1.0"
once_cell = "1"
hashbrown = "0.17"
byteorder = "1.5"
serde = { version = "1.0", features = ["derive"] }
string_cache = "0.10"
bitflags = "2.13"
bytes = "1.12"
smallvec = { version = "1.15", features = ["write"] }

[dev-dependencies]
pretty_env_logger = "0.5"
assert_matches = "1.5"
hex = "0.4"
